version: 1
filesYamlPath: ../mediascan/out/files.yaml
albumCoversPath: /var/www/html/Covers/
ageVerification: true
limitBandwidth: true
maxResults: 50000
maxResultsAlbumCovers: 500
flaskConfig:
  host: 0.0.0.0
  port: 5000
  debug: true
  rootPath: /home/brett/Git/bretttolbert/mediax/mediaserver/app
  staticUrlPath: /mediaserver/static
  urlPrefix: /mediaserver
playbackMethods:
  local:
    enabled: true
    mediaPath: /data/
  youtube:
    enabled: true
    searchQueryURLFormat: "https://www.youtube.com/results?search_query={artist}+{album}+{title}+official+music+video"
