version: 1
filesYamlPath: ../mediascan/out/files.yaml
coversPath: /var/www/html/Covers/
host: 0.0.0.0
port: 5000
debug: false
playbackMethods:
  local:
    enabled: false
    mediaPath: /data/
  youtube:
    enabled: true
    searchQueryURLFormat: "https://www.youtube.com/results?search_query={artist}+{album}+{title}+official+music+video"
